name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mongodb:
        - 4.4
        mongo_driver:
        - mongodb4
        - mongodb5
    services:
      mongodb:
        image: mongo:${{ matrix.mongodb }}
        ports:
        - 27017:27017
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
        # Use PAT instead of default Github token, because the default
        # token deliberately will not trigger another workflow run
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install
      # Skip post-install to avoid malicious scripts stealing PAT
      run: npm install --ignore-script
      env:
        # GITHUB_TOKEN can't access packages hosted in private repos,
        # even within the same organisation
        NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Post-install
      run: npm rebuild && npm run prepare --if-present
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
      env:
        MONGO_DRIVER: ${{ matrix.mongo_driver }}
    - name: Tag
      if: ${{ github.ref == 'refs/heads/main' }}
      run: ./tag.sh
